CREATE TABLE IF NOT EXISTS `yx_shellcreator_houses` (
    `id` CHAR(36) NOT NULL,
    `slug` VARCHAR(50) NOT NULL,
    `label` VARCHAR(80) NOT NULL,
    `preset_id` VARCHAR(50) NOT NULL,
    `shell_model` VARCHAR(100) NULL DEFAULT NULL,
    `bucket` INT NOT NULL,
    `environment_json` TEXT NULL,
    `access_points_json` TEXT NULL,
    `entrance_x` DOUBLE NOT NULL,
    `entrance_y` DOUBLE NOT NULL,
    `entrance_z` DOUBLE NOT NULL,
    `entrance_h` DOUBLE NOT NULL DEFAULT 0,
    `spawn_x` DOUBLE NOT NULL,
    `spawn_y` DOUBLE NOT NULL,
    `spawn_z` DOUBLE NOT NULL,
    `spawn_h` DOUBLE NOT NULL DEFAULT 0,
    `exit_x` DOUBLE NOT NULL,
    `exit_y` DOUBLE NOT NULL,
    `exit_z` DOUBLE NOT NULL,
    `exit_h` DOUBLE NOT NULL DEFAULT 0,
    `created_by` VARCHAR(80) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_yx_shellcreator_slug` (`slug`),
    UNIQUE KEY `uq_yx_shellcreator_bucket` (`bucket`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `yx_shellcreator_objects` (
    `id` CHAR(36) NOT NULL,
    `house_id` CHAR(36) NOT NULL,
    `model` VARCHAR(100) NOT NULL,
    `pos_x` DOUBLE NOT NULL,
    `pos_y` DOUBLE NOT NULL,
    `pos_z` DOUBLE NOT NULL,
    `rot_x` DOUBLE NOT NULL DEFAULT 0,
    `rot_y` DOUBLE NOT NULL DEFAULT 0,
    `rot_z` DOUBLE NOT NULL DEFAULT 0,
    `source_kind` VARCHAR(16) NOT NULL DEFAULT 'placed',
    `source_model_hash` BIGINT UNSIGNED NULL DEFAULT NULL,
    `source_pos_x` DOUBLE NULL DEFAULT NULL,
    `source_pos_y` DOUBLE NULL DEFAULT NULL,
    `source_pos_z` DOUBLE NULL DEFAULT NULL,
    `hidden` TINYINT(1) NOT NULL DEFAULT 0,
    `door_open` TINYINT(1) NOT NULL DEFAULT 0,
    `created_by` VARCHAR(80) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_yx_shellcreator_objects_house` (`house_id`),
    CONSTRAINT `fk_yx_shellcreator_objects_house`
        FOREIGN KEY (`house_id`) REFERENCES `yx_shellcreator_houses` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
